#!/bin/bash
HOME=/panfs/panasas01/sscm/qh18484
scripts=$HOME/bin/eczema_gwas_fu/bayesian_fm/finemap
gwas=/panfs/panasas01/sscm/qh18484/data/gwas/paternoster2015
onek=/panfs/panasas01/sscm/qh18484/analysis/bayesian_fm/RefPanel/1kGenomes
FINEMAP_ANALYSIS=$HOME/analysis/bayesian_fm/finemap/1k/euro
utils=$HOME/bin/eczema_gwas_fu/utils

cd $FINEMAP_ANALYSIS

function finemap_default
{
snp=$1
interval=$2
chrom=$(grep $snp $gwas/paternoster_2015_index_snps_sorted.txt | cut -f2)
cd $FINEMAP_ANALYSIS
input_file=chr${chrom}.${snp}.${interval}
mkdir -p chr${chrom}.${snp}/${interval} && cd chr${chrom}.${snp}/${interval}
python $scripts/generate_Z_file.py --tab $gwas/results.euro.pval.1k \
--proces ${onek}/${input_file}.locus2.processed --out ${input_file}.z \
--chrom 2 --pos 3 --ident 12 --ref 4 --alt 5 --beta 8 --se 9 --eas 7
rm -rf master
echo "z;ld;snp;config;log;n_samples" >master
echo "${input_file}.z;${onek}/${input_file}.locus2.ld;${input_file}.snp;${input_file}.config;${input_file}.log;103066" >>master
qsub $scripts/sub_finemap.sh
}

function finemap_haploblock
{
snp=$1
interval=$2
chrom=$(grep $snp $gwas/paternoster_2015_index_snps_sorted.txt | cut -f2)
cd $FINEMAP_ANALYSIS
input_file=${snp}.${interval}
mkdir -p chr${chrom}.${snp}/${interval} && cd chr${chrom}.${snp}/${interval}
python $scripts/generate_Z_file.py --tab $gwas/results.euro.pval.1k \
--proces ${onek}/${input_file}.processed --out ${input_file}.z \
--chrom 2 --pos 3 --ident 12 --ref 4 --alt 5 --beta 8 --se 9 --eas 7
rm -rf master
echo "z;ld;snp;config;log;n_samples" >master
echo "${input_file}.z;${onek}/${input_file}.ld;${input_file}.snp;${input_file}.config;${input_file}.log;103066" >>master
qsub $scripts/sub_finemap.sh
}


for snp in rs61813875 rs10791824 rs6419573 rs12188917 rs2212434 rs2918307 rs4809219 rs4713555 rs2041733 rs2944542 rs145809981 rs6827756 rs12730935 rs4312054 rs1249910 rs2592555 rs7127307 rs2038255 rs6602364 rs6473227 rs7512552 rs112111458 rs7625909 rs4643526 rs10199605 rs10214237 rs12951971 rs1057258 rs6872156 rs7016497 rs2905493 rs1799986 rs2227483 rs7146581 rs11657987 rs77714197 rs3917265 rs13152362 rs4705962 rs2218565 rs7512552 rs12730935 rs12295535 rs11923593 rs2143950 rs17881320 rs41293864
do
for interval in 5000 50000 250000 500000 1500000 
do
finemap_default $snp $interval
done
done

#Analysis using intervals generated by gpart and bigld.
for snp in rs61813875 rs10791824 rs6419573 rs12188917 rs2212434 rs2918307 rs4809219 rs4713555 rs2041733 rs2944542 rs145809981 rs6827756 rs12730935 rs4312054 rs1249910 rs2592555 rs7127307 rs2038255 rs6602364 rs6473227 rs7512552 rs112111458 rs7625909 rs4643526 rs10199605 rs10214237 rs12951971 rs1057258 rs6872156 rs7016497 rs2905493 rs1799986 rs2227483 rs7146581 rs11657987 rs77714197 rs3917265 rs13152362 rs4705962 rs2218565 rs7512552 rs12730935 rs12295535 rs11923593 rs2143950 rs17881320 rs41293864
do
for interval in gpart bigld
do
finemap_haploblock $snp $interval
done
done

FINEMAP_ANALYSIS_copy=/panfs/panasas01/sscm/qh18484/analysis/bayesian_fm/finemap/1k/euro/copy
cp -r $FINEMAP_ANALYSIS/chr* $FINEMAP_ANALYSIS_copy

#Rename output file from haploblock analysis so that file names follow the same convention as for intervals, ie. chromosome number first in the filename.
for snp in rs61813875 rs10791824 rs6419573 rs12188917 rs2212434 rs2918307 rs4809219 rs4713555 rs2041733 rs2944542 rs145809981 rs6827756 rs12730935 rs4312054 rs1249910 rs2592555 rs7127307 rs2038255 rs6602364 rs6473227 rs7512552 rs112111458 rs7625909 rs4643526 rs10199605 rs10214237 rs12951971 rs1057258 rs6872156 rs7016497 rs2905493 rs1799986 rs2227483 rs7146581 rs11657987 rs77714197 rs3917265 rs13152362 rs4705962 rs2218565 rs7512552 rs12730935 rs12295535 rs11923593 rs2143950 rs17881320 rs41293864
do
for interval in gpart bigld
do
chrom=$(grep $snp $gwas/paternoster_2015_index_snps_sorted.txt | cut -f2)
cd $FINEMAP_ANALYSIS_copy
cd chr${chrom}.${snp}/${interval}
mv ${snp}.${interval}.snp chr${chrom}.${snp}.${interval}.snp
mv ${snp}.${interval}.config chr${chrom}.${snp}.${interval}.config
mv ${snp}.${interval}.z chr${chrom}.${snp}.${interval}.z
done
done

