cd /mnt/storage/home/qh18484/scratch/GTEx_V8_complete
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Alasoo_2018/ge/Alasoo_2018_ge_macrophage_naive.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Alasoo_2018/ge/Alasoo_2018_ge_macrophage_IFNg.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Alasoo_2018/ge/Alasoo_2018_ge_macrophage_Salmonella.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Alasoo_2018/ge/Alasoo_2018_ge_macrophage_IFNg+Salmonella.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/BLUEPRINT/ge/BLUEPRINT_ge_monocyte.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/BLUEPRINT/ge/BLUEPRINT_ge_neutrophil.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/BLUEPRINT/ge/BLUEPRINT_ge_T-cell.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GENCORD/ge/GENCORD_ge_LCL.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GENCORD/ge/GENCORD_ge_fibroblast.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GENCORD/ge/GENCORD_ge_T-cell.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GEUVADIS/ge/GEUVADIS_ge_LCL.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Lepik_2017/ge/Lepik_2017_ge_blood.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Nedelec_2016/ge/Nedelec_2016_ge_macrophage_Listeria.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Nedelec_2016/ge/Nedelec_2016_ge_macrophage_naive.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Nedelec_2016/ge/Nedelec_2016_ge_macrophage_Salmonella.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Quach_2016/ge/Quach_2016_ge_monocyte_naive.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Quach_2016/ge/Quach_2016_ge_monocyte_LPS.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Quach_2016/ge/Quach_2016_ge_monocyte_Pam3CSK4.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Quach_2016/ge/Quach_2016_ge_monocyte_R848.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Quach_2016/ge/Quach_2016_ge_monocyte_IAV.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Tfh_memory.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Th17_memory.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Th1_memory.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Th2_memory.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Th1-17_memory.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Treg_memory.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Treg_naive.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_B-cell_naive.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_CD4_T-cell_naive.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_CD4_T-cell_anti-CD3-CD28.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_CD8_T-cell_naive.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_CD8_T-cell_anti-CD3-CD28.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_monocyte_CD16_naive.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_monocyte_naive.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_NK-cell_naive.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/TwinsUK/ge/TwinsUK_ge_LCL.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/TwinsUK/ge/TwinsUK_ge_skin.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/TwinsUK/ge/TwinsUK_ge_blood.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Cells_Cultured_fibroblasts.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Cells_EBV-transformed_lymphocytes.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Colon_Sigmoid.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Colon_Transverse.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Esophagus_Mucosa.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Lung.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Skin_Not_Sun_Exposed_Suprapubic.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Skin_Sun_Exposed_Lower_leg.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Small_Intestine_Terminal_Ileum.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Spleen.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Whole_Blood.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Alasoo_2018/ge/Alasoo_2018_ge_macrophage_naive.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Alasoo_2018/ge/Alasoo_2018_ge_macrophage_IFNg.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Alasoo_2018/ge/Alasoo_2018_ge_macrophage_Salmonella.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Alasoo_2018/ge/Alasoo_2018_ge_macrophage_IFNg+Salmonella.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/BLUEPRINT/ge/BLUEPRINT_ge_monocyte.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/BLUEPRINT/ge/BLUEPRINT_ge_neutrophil.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/BLUEPRINT/ge/BLUEPRINT_ge_T-cell.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GENCORD/ge/GENCORD_ge_LCL.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GENCORD/ge/GENCORD_ge_fibroblast.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GENCORD/ge/GENCORD_ge_T-cell.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GEUVADIS/ge/GEUVADIS_ge_LCL.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Lepik_2017/ge/Lepik_2017_ge_blood.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Nedelec_2016/ge/Nedelec_2016_ge_macrophage_Listeria.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Nedelec_2016/ge/Nedelec_2016_ge_macrophage_naive.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Nedelec_2016/ge/Nedelec_2016_ge_macrophage_Salmonella.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Quach_2016/ge/Quach_2016_ge_monocyte_naive.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Quach_2016/ge/Quach_2016_ge_monocyte_LPS.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Quach_2016/ge/Quach_2016_ge_monocyte_Pam3CSK4.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Quach_2016/ge/Quach_2016_ge_monocyte_R848.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Quach_2016/ge/Quach_2016_ge_monocyte_IAV.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Tfh_memory.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Th17_memory.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Th1_memory.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Th2_memory.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Th1-17_memory.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Treg_memory.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Treg_naive.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_B-cell_naive.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_CD4_T-cell_naive.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_CD4_T-cell_anti-CD3-CD28.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_CD8_T-cell_naive.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_CD8_T-cell_anti-CD3-CD28.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_monocyte_CD16_naive.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_monocyte_naive.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_NK-cell_naive.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/TwinsUK/ge/TwinsUK_ge_LCL.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/TwinsUK/ge/TwinsUK_ge_skin.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/TwinsUK/ge/TwinsUK_ge_blood.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Cells_Cultured_fibroblasts.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Cells_EBV-transformed_lymphocytes.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Colon_Sigmoid.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Colon_Transverse.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Esophagus_Mucosa.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Lung.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Skin_Not_Sun_Exposed_Suprapubic.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Skin_Sun_Exposed_Lower_leg.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Small_Intestine_Terminal_Ileum.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Spleen.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/GTEx_V8/ge/Whole_Blood.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_T-cell_CD8.all.tsv.gz                          
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_T-cell_CD4.all.tsv.gz                          
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_transverse_colon.all.tsv.gz                    
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_monocyte_CD14.all.tsv.gz                       
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_neutrophil_CD15.all.tsv.gz                     
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_platelet.all.tsv.gz                            
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_rectum.all.tsv.gz                              
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_B-cell_CD19.all.tsv.gz                         
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_ileum.all.tsv.gz                               
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_T-cell_CD8.all.tsv.gz.tbi                          
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_T-cell_CD4.all.tsv.gz.tbi                          
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_transverse_colon.all.tsv.gz.tbi                    
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_monocyte_CD14.all.tsv.gz.tbi                       
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_neutrophil_CD15.all.tsv.gz.tbi                     
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_platelet.all.tsv.gz.tbi                            
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_rectum.all.tsv.gz.tbi                              
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_B-cell_CD19.all.tsv.gz.tbi                         
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/CEDAR/microarray/CEDAR_microarray_ileum.all.tsv.gz.tbi        
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Fairfax_2012/microarray/Fairfax_2012_microarray_B-cell_CD19.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Fairfax_2014/microarray/Fairfax_2014_microarray_monocyte_naive.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Fairfax_2014/microarray/Fairfax_2014_microarray_monocyte_IFN24.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Fairfax_2014/microarray/Fairfax_2014_microarray_monocyte_LPS2.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Fairfax_2014/microarray/Fairfax_2014_microarray_monocyte_LPS24.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Kasela_2017/microarray/Kasela_2017_microarray_T-cell_CD4.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Kasela_2017/microarray/Kasela_2017_microarray_T-cell_CD8.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Naranbhai_2015/microarray/Naranbhai_2015_microarray_neutrophil_CD16.all.tsv.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Fairfax_2012/microarray/Fairfax_2012_microarray_B-cell_CD19.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Fairfax_2014/microarray/Fairfax_2014_microarray_monocyte_naive.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Fairfax_2014/microarray/Fairfax_2014_microarray_monocyte_IFN24.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Fairfax_2014/microarray/Fairfax_2014_microarray_monocyte_LPS2.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Fairfax_2014/microarray/Fairfax_2014_microarray_monocyte_LPS24.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Kasela_2017/microarray/Kasela_2017_microarray_T-cell_CD4.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Kasela_2017/microarray/Kasela_2017_microarray_T-cell_CD8.all.tsv.gz.tbi
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Naranbhai_2015/microarray/Naranbhai_2015_microarray_neutrophil_CD16.all.tsv.gz.tbi

